### ISSUE TITLE
Incompatibility of subfiles 2.0 with lualatex 1.12.0 (TeX Live 2020) LaTeX2e <2020-10-01> pre-release-9

### ISSUE THREAD

**Issue by yuishin-kikuchi** [gsalzer/subfiles#10]
Hi, gsalzer!
I really love subfiles package.

I've updated my TeX Live environment just now and LaTeX was updated (revision 56514).
I've read subfiles.pdf and I believe that version 2.0 works with new LaTeX.

Unfortunately, the compilation fails:

%% test.tex
\documentclass{article}
\usepackage{subfiles}
\begin{document}
\subfile{sections/sectest}
\end{document}

%% sections/sectest.tex
\documentclass[../test]{subfiles}
\begin{document}
\[ABC\]
\end{document}

How to avoid errors?
Thanks.

**Comment by gsalzer** [comment]
Hi yuishin-kikuchi, I cannot reproduce the issue. Compiling your example, test.tex as well as sectest.tex, with (pdf)latex as well as (pdf)latex-dev from the current TeX Live 2020 distribution works without problems. The two versions:

- (pdf)latex
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-24>
 *File List*
 article.cls    2019/12/20 v1.4l Standard LaTeX document class
  size10.clo    2019/12/20 v1.4l Standard LaTeX file (size option)
subfiles.sty    2020/09/07 v2.0 Multi-file projects (package)
  import.sty    2020/04/01  v 6.2
l3backend-pdftex.def    2020-09-24 L3 backend support: PDF output (pdfTeX)
```
- (pdf)latex-dev
```
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex-dev)
LaTeX2e <2020-10-01> pre-release-9 (develop 2020-9-27 branch)
L3 programming layer <2020-09-24> xparse <2020-03-03>
 *File List*
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
subfiles.sty    2020/09/07 v2.0 Multi-file projects (package)
  import.sty    2020/04/01  v 6.2
l3backend-pdftex.def    2020-09-24 L3 backend support: PDF output (pdfTeX)
```

Can you please re-check your setup and explain in more detail which errors you encounter? What does the log file say?

**Comment by yuishin-kikuchi** [comment]
Thanks to reply, gsalzer.

I checked subfiles.sty in my environment and the version is true 2020/09/07.
I'm using LuaLaTeX.

```
This is LuaHBTeX, Version 1.12.0 (TeX Live 2020/W32TeX) 
 restricted system commands enabled.

LaTeX2e <2020-10-01>

 L3 programming layer <2020-09-24> xparse <2020-03-03> (c:/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(c:/texlive/2020/texmf-dist/tex/latex/base/size10.clo)) (c:/texlive/2020/texmf-dist/tex/latex/subfiles/subfiles.sty (c:/texlive/2020/texmf-dist/tex/latex/import/import.sty)) (c:/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)
No file test.aux.
(c:/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd) (./sections/sectest.tex
./sections/sectest.tex:4: Missing number, treated as zero.
<to be read again> 
=
l.4 \end{document}
```

**Comment by gsalzer** [comment]
Thanks for reporting the issue. I can now reproduce the error.

**Comment by yuishin-kikuchi** [comment]
Hi, gsalzer.

Almost same problem occurred with standalone package.
I saw tickets of standalone package in source forge:
https://sourceforge.net/p/standalone/tickets/2/

Ulrike Fischer said,
"the problem has been resolved in l3kernel, the document compiles for me now."

In short, this problem was not in subfiles but in L3 kernel.
Soon the bug is removed.
Anyway, thanks!

**Comment by gsalzer** [comment]
@yuishin-kikuchi Thanks for the update!
