### ISSUE TITLE
Indenting \begin{document} in subfiles breaks compilation

### ISSUE THREAD

**Issue by jlelong** [gsalzer/subfiles#13]
Consider the following example

main.tex

```latex
\documentclass{article}
\usepackage{subfiles}
\begin{document}
  main
  \subfile{sub/a}
\end{document}
````

sub/a.tex
```latex
\documentclass[../main.tex]{subfiles}
 \begin{document}
sub sub sub
\end{document}
```

Note the space before `\begin{document}`. Running `latex main` yields the error
```
Runaway argument?
! File ended while scanning use of \subfiles@tmp.
<inserted text>
                \par
l.5 \subfile{sub/a}
```

Removing the leading space in front of `\begin{document}` fixes the issue.

This happens with `subfiles` `v2.0`.

**Comment by gsalzer** [comment]
This is to be expected. v2.0 uses still the same technique for skipping stuff as, say the verbatim or comment package. For this to work, it is necessary that `\begin{document}` starts at the beginning of the line. See also the tips in the trouble-shooting section of the documentation.

The next version, v2.1, uses another method for skipping the preamble, which ignores these spaces. This version is currently only available on Github, see `subfiles.sty` in the top directory.

**Comment by jlelong** [comment]
Thanks for your detailed answer and sorry for not reading the troubleshooting section carefully enough.

**Comment by gsalzer** [comment]
No need to be sorry. The old behavior of `subfiles` is surprising for a normal user, it is reasonable to fix it. And who reads the docs anyway? ;-)

**Comment by gsalzer** [comment]
And thanks for reporting! Better to report than to live with the bugs ...
