### ISSUE TITLE
Extra space under threeparttable and footnotes

### ISSUE THREAD

**Issue by kalekje** [gsalzer/subfiles#18]
Hello, please see the following Q on Stack Exchange. I believe I've narrowed the issue down to the subfiles package. Note that I recently updated to the newest version.

https://tex.stackexchange.com/questions/571493/strange-behaviour-with-tablenotes-and-threeparttable-spacing-upon-updating-mikte?noredirect=1#comment1439988_571493

**Comment by gsalzer** [comment]
Please upgrade the subfiles package to version v2.2 (2020/11/14) and check if the problem persists. Your problems looks like the one that v2.2 is supposed to fix. I tried with the sample code that you provide on TeX.SX, and it seems to work.

v2.2 is available from CTAN or from Github (see the top directory of the repository).

In any case thanks a lot for reporting the issue! Efforts like yours contribute to fix problems as quickly as possible.

**Comment by kalekje** [comment]
To confirm on how I should manually upgrade via MiKTeX:

Just place the newest files on GIT in these folders:

![image](https://user-images.githubusercontent.com/51413662/99673613-9cad3980-2a3a-11eb-
8fe0-9f7b3bfffb15.png)
