### ISSUE TITLE
`tlmgr` miss `xpatch` as depedency.

### ISSUE THREAD

**Issue by y-marui** [gsalzer/subfiles#30]
I set up latex on the new machine with BasicTeX.
Even after running `sudo tlmgr install subfiles`, latex return `xpatch` was not found error.

**Comment by gsalzer** [comment]
Apparently you use the `standalone` package. In this case `subfiles` needs the package `xpatch`. This is what the error message tells. So either don't load the `standalone` package (if you don't really use it), or do `sudo tlmgr install xpatch`.

**Comment by gsalzer** [comment]
Thanks for the report. I've added a `DEPENDS.txt` file. When it makes it into the next TeXLive distribution, `tlmgr` will maybe install xpatch automatically together with subfiles.
