### ISSUE TITLE
Incompabability with import package version 6.0 

### ISSUE THREAD

**Issue by samcarter** [gsalzer/subfiles#6]
After the update of the import package from 5.1 to 6.0 the following example stopped working

```
\documentclass{book}

\usepackage{subfiles}

\begin{filecontents*}{file.tex}
\documentclass[document]{subfiles}

\begin{document}

test

\end{document}

\end{filecontents*}

\begin{document}

\subfile{file}

\end{document}
```

with the error

```
! LaTeX Error: File `document.aux' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: aux)

Enter file name: 
! Emergency stop.
<read *> 
         
l.19 \subfile{file}
                   ^^M
*** (cannot \read from terminal in nonstop modes)
```

Is this something you can fix or should I report this to the import package author?

**Comment by gvdeynde** [comment]
I also had weird issues with the new version of import.sty and subfiles. Suddenly, LaTeX couldn't find an image anymore (other images in the same folder were ok). And running LaTeX on a subfile (where one would expect to have only that part rendered but with the preamble of the main document included) the compilation also broke off. Putting the previous version of import.sty in my document directory solved the problem...

**Comment by gsalzer** [comment]
Thanks for reporting the problem, I will think about it. Probably `subfiles` should not depend on `import`; it isn't a perfect fit anyway.

**Comment by samcarter** [comment]
Import package has just been patched

https://lists.dante.de/pipermail/ctan-ann/2020-March/013656.html

**Comment by gsalzer** [comment]
Thanks for the follow up!

**Comment by gsalzer** [comment]
@samcarter Unrelated: Can you point to me to any discussions on tex.sx that help me to understand the reasons why you left tex.sx? I'm less active there since a while, and the Monica case was the last meta-discussion about stackexchange that I'm aware of. Or send me a private mail (search for 'gsalzer logic').
