### ISSUE TITLE
subfiles with citations

### ISSUE THREAD

**Issue by alan-isaac** [gsalzer/subfiles#7]
There is a major problem with the use of subfiles: bibtex is still the most popular citation tool, and compiling subfiles with bibitex does not usefully work.

1. The "hint" in the docs is completely inadequate; please fix.

2. Please add real support in some form.  At the very least, somthing like this:
  https://tex.stackexchange.com/questions/535834/how-to-compile-subfiles-with-bibtex-citations/536008 (It works.)

Thank you.

**Comment by gsalzer** [comment]
@alan-isaac 
Thanks for reporting the issue and providing the link to tex.stackexchange.
The problem should be resolved now in version 2.0, available from github and, shortly, from CTAN.
Please let me now if encounter any further problems.
