### ISSUE TITLE
subfiles needs to be adapted to the next latex version

### ISSUE THREAD

**Issue by u-fischer** [gsalzer/subfiles#8]
We just released a new development version of the next LaTeX version,
In this dev release we implemented a new hook system and extended the existing set of hooks.

Details can be found in the announcement:
https://www.latex-project.org/news/2020/07/22/latex-dev-2020-10-1b/

This changes break with subfiles as it redefines \document/\enddocument in an incompatible way.

~~~~
% main.tex
\documentclass{article}
\usepackage{subfiles}
\begin{document}
\subfile{sub.tex}
\end{document}
~~~~

~~~~
% sub.tex
\documentclass[main.tex]{subfiles}
\begin{document}
hello
\end{document}
~~~~

gives if `sub.tex` is compiled with pdflatex.dev

~~~~
! Extra \endgroup.
<recently read> \endgroup 
                          
l.5 \end{document}
~~~~

Please adapt subfiles so that is doesn't fail when the final release in October hits the streets.

If you need help with the implementation or have questions please open an issue at the latex2e github.

Some suggestion about an implementation that allows the package to work with older and newer formats can be found here:
https://listserv.uni-heidelberg.de/cgi-bin/wa?A2=LATEX-L;22740d74.2007&S=

Ulrike Fischer, LaTeX team

**Comment by gsalzer** [comment]
Thanks for the notification. I will look at it.

**Comment by gsalzer** [comment]
@u-fischer 
Version 2.0 of the package, published just now on github and available soon on CTAN, is compatible with the upcoming release of LaTeX (as well as with the old one). Thanks again for the heads-up!
